import type { ShipState, Port } from '@/types/fleet'

export const PORTS: Port[] = [
  { id: 'port-dubai', name: 'Dubai (Jebel Ali)', position: { lat: 24.9857, lng: 55.0272 } },
  { id: 'port-abu-dhabi', name: 'Abu Dhabi', position: { lat: 24.4667, lng: 54.3667 } },
  { id: 'port-muscat', name: 'Muscat', position: { lat: 23.6139, lng: 58.5922 } },
  { id: 'port-bandar-abbas', name: 'Bandar Abbas', position: { lat: 27.1832, lng: 56.2666 } },
  { id: 'port-kuwait', name: 'Kuwait', position: { lat: 29.3697, lng: 47.9783 } },
  { id: 'port-doha', name: 'Doha', position: { lat: 25.2854, lng: 51.531 } },
]

export const NAVIGABLE_WATER: [number, number][] = [
  [30.0, 48.5], [30.2, 50.0], [30.0, 52.0], [29.5, 54.0],
  [28.5, 56.0], [27.5, 56.8], [26.5, 57.2], [25.5, 57.8],
  [24.5, 58.5], [23.5, 59.0], [22.5, 59.5], [22.0, 58.0],
  [22.5, 56.0], [23.0, 54.0], [23.5, 52.0], [24.0, 50.0],
  [24.5, 48.5], [25.5, 48.0], [27.0, 48.5], [28.5, 48.5],
  [30.0, 48.5],
]

export const INITIAL_SHIPS: ShipState[] = [
  {
    id: 'MV-01', name: 'MV Hormuz Star',
    position: { lat: 26.5, lng: 56.3 },
    speed: 12, heading: 270,
    destinationPortId: 'port-dubai',
    fuelRemaining: 85, cargo: 'Crude Oil',
    status: 'normal', route: [], weatherPenalty: false, lastUpdated: Date.now(),
  },
  {
    id: 'MV-02', name: 'MV Gulf Falcon',
    position: { lat: 25.8, lng: 57.1 },
    speed: 10, heading: 285,
    destinationPortId: 'port-abu-dhabi',
    fuelRemaining: 70, cargo: 'LNG',
    status: 'normal', route: [], weatherPenalty: false, lastUpdated: Date.now(),
  },
  {
    id: 'MV-03', name: 'MV Oman Pride',
    position: { lat: 24.2, lng: 58.8 },
    speed: 14, heading: 315,
    destinationPortId: 'port-bandar-abbas',
    fuelRemaining: 60, cargo: 'Container',
    status: 'normal', route: [], weatherPenalty: false, lastUpdated: Date.now(),
  },
  {
    id: 'MV-04', name: 'MV Persian Wind',
    position: { lat: 27.0, lng: 55.5 },
    speed: 8, heading: 260,
    destinationPortId: 'port-kuwait',
    fuelRemaining: 90, cargo: 'Refined Fuel',
    status: 'normal', route: [], weatherPenalty: false, lastUpdated: Date.now(),
  },
  {
    id: 'MV-05', name: 'MV Doha Express',
    position: { lat: 26.0, lng: 54.0 },
    speed: 11, heading: 250,
    destinationPortId: 'port-doha',
    fuelRemaining: 75, cargo: 'General Cargo',
    status: 'normal', route: [], weatherPenalty: false, lastUpdated: Date.now(),
  },
  {
    id: 'MV-06', name: 'MV Al Rashid',
    position: { lat: 25.5, lng: 56.8 },
    speed: 9, heading: 270,
    destinationPortId: 'port-dubai',
    fuelRemaining: 55, cargo: 'Chemicals',
    status: 'normal', route: [], weatherPenalty: false, lastUpdated: Date.now(),
  },
  {
    id: 'MV-07', name: 'MV Crisis Runner',
    position: { lat: 26.8, lng: 56.1 },
    speed: 7, heading: 280,
    destinationPortId: 'port-muscat',
    fuelRemaining: 18, cargo: 'Steel',
    status: 'insufficient_fuel', route: [], weatherPenalty: false, lastUpdated: Date.now(),
  },
  {
    id: 'MV-08', name: 'MV Strait Drifter',
    position: { lat: 26.2, lng: 57.4 },
    speed: 13, heading: 295,
    destinationPortId: 'port-abu-dhabi',
    fuelRemaining: 80, cargo: 'Livestock',
    status: 'normal', route: [], weatherPenalty: false, lastUpdated: Date.now(),
  },
  {
    id: 'MV-09', name: 'MV Gulf Horizon',
    position: { lat: 25.0, lng: 55.8 },
    speed: 10, heading: 260,
    destinationPortId: 'port-kuwait',
    fuelRemaining: 65, cargo: 'Vehicles',
    status: 'normal', route: [], weatherPenalty: false, lastUpdated: Date.now(),
  },
  {
    id: 'MV-10', name: 'MV Iron Sheikh',
    position: { lat: 27.5, lng: 55.0 },
    speed: 12, heading: 240,
    destinationPortId: 'port-doha',
    fuelRemaining: 72, cargo: 'Iron Ore',
    status: 'normal', route: [], weatherPenalty: false, lastUpdated: Date.now(),
  },
  {
    id: 'MV-11', name: 'MV Bandar Queen',
    position: { lat: 27.2, lng: 56.8 },
    speed: 9, heading: 315,
    destinationPortId: 'port-bandar-abbas',
    fuelRemaining: 88, cargo: 'Electronics',
    status: 'normal', route: [], weatherPenalty: false, lastUpdated: Date.now(),
  },
  {
    id: 'MV-12', name: 'MV Sand Viper',
    position: { lat: 24.8, lng: 57.0 },
    speed: 11, heading: 270,
    destinationPortId: 'port-dubai',
    fuelRemaining: 50, cargo: 'Grain',
    status: 'normal', route: [], weatherPenalty: false, lastUpdated: Date.now(),
  },
  {
    id: 'MV-13', name: 'MV Khasab Arrow',
    position: { lat: 26.1, lng: 56.5 },
    speed: 8, heading: 280,
    destinationPortId: 'port-muscat',
    fuelRemaining: 40, cargo: 'Timber',
    status: 'normal', route: [], weatherPenalty: false, lastUpdated: Date.now(),
  },
  {
    id: 'MV-14', name: 'MV Musandam Star',
    position: { lat: 26.7, lng: 56.7 },
    speed: 14, heading: 265,
    destinationPortId: 'port-abu-dhabi',
    fuelRemaining: 93, cargo: 'Machinery',
    status: 'normal', route: [], weatherPenalty: false, lastUpdated: Date.now(),
  },
  {
    id: 'MV-15', name: 'MV Gulf Phantom',
    position: { lat: 25.3, lng: 57.6 },
    speed: 10, heading: 300,
    destinationPortId: 'port-bandar-abbas',
    fuelRemaining: 30, cargo: 'Fuel Oil',
    status: 'normal', route: [], weatherPenalty: false, lastUpdated: Date.now(),
  },
]
